language: node_js
node_js:
- "6.10.3"
script: "cd server && npm run-script integrate1"
# sendcoverage to coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

